package compiler.javacc;

/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int CHARACTER = 3;
  /** RegularExpression Id. */
  int ID = 4;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int REAL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "<DIGIT>",
    "<CHARACTER>",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<token of kind 7>",
    "\"\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"class\"",
    "\"{\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"(\"",
    "\"String\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\"extends\"",
    "\";\"",
    "\"return\"",
    "\",\"",
    "\"int\"",
    "\"boolean\"",
    "\"=\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"!\"",
  };

}
