/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package compiler.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int WHILE = 2;
  /** RegularExpression Id. */
  int PUBLIC = 3;
  /** RegularExpression Id. */
  int STATIC = 4;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int CHARACTER = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int NUM = 15;
  /** RegularExpression Id. */
  int REAL = 16;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"while\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "<DIGIT>",
    "<CHARACTER>",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<INTEGER_LITERAL>",
    "<token of kind 18>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\";\"",
  };

}
