/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package compiler.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int WHILE = 2;
  /** RegularExpression Id. */
  int PUBLIC = 3;
  /** RegularExpression Id. */
  int STATIC = 4;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int RETURN = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int CHARACTER = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int NUM = 18;
  /** RegularExpression Id. */
  int REAL = 19;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"while\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"extends\"",
    "\"return\"",
    "\"String\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"else\"",
    "<DIGIT>",
    "<CHARACTER>",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<INTEGER_LITERAL>",
    "<token of kind 21>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"System.out.println\"",
    "\"=\"",
  };

}
