/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package compiler.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int WHILE = 2;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int CHARACTER = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"while\"",
    "\"if\"",
    "<DIGIT>",
    "<CHARACTER>",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<INTEGER_LITERAL>",
    "<token of kind 10>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
  };

}
